### ISSUE TITLE
What do to about SCMP

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-research_I-D#5]
How do we position SCMP? Shall it be authenticated? 

Context: In the dataplane draft we had to adjust text to find a proper reference to the SCMP doc. Also the scionproto SCMP doc had to be updated. References: 
- https://github.com/scionassociation/scion-dp_I-D/issues/8
- https://github.com/scionproto/scion/issues/4528

**Comment by juagargi** [comment]
Closed by #20
