### ISSUE TITLE
Expand transport layer

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-research_I-D#8]
- [x] Mentions implications of MP-QUIC and recent changes related to path-IDs #14 
- [x] TAPS/PANAPI

As guidance use rfc9217: ` 2.5.  Implications of Path Awareness for the Transport and Application Layers`

**Comment by tzaeschke** [comment]
@nicorusti Sorry, I must have missed that yesterday. Could you remind me what should  I to write about TAPS/PANAPI? I am not really familiar with these...
